#!/broad/sankaranlab/kgarg/scripts/pearson/venv3/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'mgatk','console_scripts','mgatk'
__requires__ = 'mgatk'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mgatk', 'console_scripts', 'mgatk')()
    )
