#!/broad/sankaranlab/kgarg/scripts/pearson/venv3/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'snakemake','console_scripts','snakemake'
__requires__ = 'snakemake'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('snakemake', 'console_scripts', 'snakemake')()
    )
